// Auto-generated by scripts/refresh_ctis.py — do not edit by hand.
window.CTIS_LIVE = {
  updated: '2026-04-20',
  countries: {
  "Czechia": 0,
  "Germany": 0,
  "Spain": 0,
  "France": 0,
  "Italy": 0,
  "Poland": 0,
  "Belgium": 0,
  "Netherlands": 0,
  "Denmark": 0,
  "Hungary": 0,
  "Austria": 0,
  "Sweden": 0
}
};
