# scripts/refresh_ctis.py
# Pulls aggregate numbers from the CTIS public API and writes data.js.
# Runs nightly on GitHub Actions — you don't need to run it yourself.

import json, urllib.request, urllib.parse, datetime, pathlib

CTIS = "https://euclinicaltrials.eu/ctis-public-api/search"
COUNTRIES = ["Czechia","Germany","Spain","France","Italy","Poland",
             "Belgium","Netherlands","Denmark","Hungary","Austria","Sweden"]

def query(country):
    body = json.dumps({
        "pagination": {"page": 1, "size": 1},
        "searchCriteria": {"containAll": "", "containAny": "",
                           "containNot": "", "memberStates": [country]}
    }).encode()
    req = urllib.request.Request(CTIS, data=body,
        headers={"Content-Type": "application/json"})
    with urllib.request.urlopen(req, timeout=30) as r:
        return json.loads(r.read())

results = {}
for c in COUNTRIES:
    try:
        data = query(c)
        results[c] = data.get("totalSize", 0)
        print(f"{c}: {results[c]} trials")
    except Exception as e:
        print(f"{c}: FAILED ({e})")

stamp = datetime.date.today().isoformat()
out = pathlib.Path("data.live.js")
out.write_text(
    "// Auto-generated by scripts/refresh_ctis.py — do not edit by hand.\n"
    f"window.CTIS_LIVE = {{\n  updated: '{stamp}',\n"
    f"  countries: {json.dumps(results, indent=2)}\n}};\n"
)
print(f"Wrote {out} on {stamp}")
